"""first commit

Revision ID: 4b24ebe0871d
Revises: 
Create Date: 2022-06-14 12:09:53.498839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b24ebe0871d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.Column("domain_name", sa.Unicode(length=65), nullable=False),
        sa.Column("domain_type", sa.Unicode(length=50), nullable=False),
        sa.Column("domain_isactive", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("domain_id"),
    )
    op.create_index(
        op.f("ix_domains_domain_name"), "domains", ["domain_name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("role", sa.Integer(), nullable=True),
        sa.Column("password", sa.String(length=500), nullable=True),
        sa.Column("password_q", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user"),
    )
    op.create_table(
        "statistics",
        sa.Column("stats_id", sa.Unicode(length=128), nullable=False),
        sa.Column("stats_domain_id", sa.Integer(), nullable=False),
        sa.Column("stats_client_ip", sa.Unicode(length=45), nullable=True),
        sa.Column("stats_request_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stats_domain_id"],
            ["domains.domain_id"],
        ),
        sa.PrimaryKeyConstraint("stats_id"),
        sa.UniqueConstraint(
            "stats_domain_id", "stats_client_ip", name="couple_ip_domain"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("statistics")
    op.drop_table("users")
    op.drop_index(op.f("ix_domains_domain_name"), table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
